spring:
  application:
    name: notification-service
  mongodb:
    username: sonny
    password: sonny
    host: localhost
    port: 27017
    database: notification
    authentication-database: admin
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.sonny.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.sonny.ecommerce.kafka.payment.PaymentConfirmation
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    username: sonny
    password: sonny
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: 8040