spring:
  application:
    name: notification-service
  mongodb:
    username: sonny
    password: sonny
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.sonny.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.sonny.ecommerce.notification.PaymentConfirmation
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: sonny
    password: sonny
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040